const CONFIG_SERVER = 'config-server'
const ENV_BUILD_WHERE_PRODUCE = 'PRODUCE'
const ENV_BUILD_WHERE_DEBUG_OFFICE = 'DEBUG_OFFICE'
const ENV_BUILD_WHERE_DEBUG_HOME = 'DEBUG_HOME'
const ENV_BUILD_TARGET_WSY = 'WSY'
const ENV_BUILD_TARGET_BC = 'BC'
const SERVER_GEN = 'server-gen'
const STG_SESSION_KEY_NAME = 'gen_session_key'
const STG_CHANNEL_UNIT = 'channel-unit'
const STG_SPLASH_BACK_IMG = 'splash-back-img'
const STG_NEW_ADDED = 'new_added'
const STG_SHOPPING_CART = 'shopping-cart'
const STG_ORDER_CONFIRM_NOW = 'order-confirm-now'
const STG_ORDER_CONFIRM_SHOW_ORDER_ITEMS = 'order-confirm-show-order-items'
const STG_ORDER_IS_CHANGED = 'order-is-changed'
const ORDER_CONFIRM_SOURCE_SPU_DETAILS = 'spu-details'
const ORDER_CONFIRM_SOURCE_SHOPPING_CART = 'shopping-cart'

module.exports = {
    CONFIG_SERVER,
    ENV_BUILD_WHERE_PRODUCE,
    ENV_BUILD_WHERE_DEBUG_OFFICE,
    ENV_BUILD_WHERE_DEBUG_HOME,
    ENV_BUILD_TARGET_WSY,
    ENV_BUILD_TARGET_BC,
    SERVER_GEN,
    STG_SESSION_KEY_NAME,
    STG_CHANNEL_UNIT,
    STG_SPLASH_BACK_IMG,
    STG_NEW_ADDED,
    STG_SHOPPING_CART,
    STG_ORDER_CONFIRM_NOW,
    STG_ORDER_CONFIRM_SHOW_ORDER_ITEMS,
    STG_ORDER_IS_CHANGED,
    ORDER_CONFIRM_SOURCE_SPU_DETAILS,
    ORDER_CONFIRM_SOURCE_SHOPPING_CART
}