const CONFIG_SERVER = 'config-server'
const ENV_BUILD_WHERE_PRODUCE = 'PRODUCE'
const ENV_BUILD_WHERE_DEBUG_OFFICE = 'DEBUG_OFFICE'
const ENV_BUILD_WHERE_DEBUG_HOME = 'DEBUG_HOME'
const ENV_BUILD_TARGET_WSY = 'WSY'
const SERVER_GEN = 'server-gen'
const STG_SESSION_KEY_NAME = 'gen_session_key'
const STG_CHANNEL_UNIT = 'channel-unit'
const STG_SPLASH_BACK_IMG = 'splash-back-img'
const G_ON_SHOW_NEW_ATTACH_DEVICE = 'g_on_show_new_attach_device'

module.exports = {
    CONFIG_SERVER,
    ENV_BUILD_WHERE_PRODUCE,
    ENV_BUILD_WHERE_DEBUG_OFFICE,
    ENV_BUILD_WHERE_DEBUG_HOME,
    ENV_BUILD_TARGET_WSY,
    SERVER_GEN,
    STG_SESSION_KEY_NAME,
    STG_CHANNEL_UNIT,
    STG_SPLASH_BACK_IMG,
    G_ON_SHOW_NEW_ATTACH_DEVICE
}